/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package painter;

import java.awt.Color;

/**
 *
 * @author eslam
 */
public class ButtonPanel extends javax.swing.JPanel {
    private ShapeType selectedShape=ShapeType.RECTANGLE;
    private Color selectedColor = Color.WHITE;
    private boolean select;

    public boolean isSelect() {
        return select;
    }

    public void setSelect(boolean select) {
        this.select = select;
    }
    
    /**
     * Creates new form ButtonPanel
     */
    public ButtonPanel() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        SelectButton = new javax.swing.JToggleButton();
        RectangleButton = new javax.swing.JToggleButton();
        TriangleButton = new javax.swing.JToggleButton();
        OvalButton = new javax.swing.JToggleButton();
        HexgeonButton = new javax.swing.JToggleButton();
        RedColor = new javax.swing.JToggleButton();
        GreenColor = new javax.swing.JToggleButton();
        BlackColor = new javax.swing.JToggleButton();
        BlueColor = new javax.swing.JToggleButton();
        White = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridLayout(0, 2));

        buttonGroup1.add(SelectButton);
        SelectButton.setText("Select");
        SelectButton.setMaximumSize(new java.awt.Dimension(50, 22));
        SelectButton.setPreferredSize(new java.awt.Dimension(50, 22));
        SelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButtonActionPerformed(evt);
            }
        });
        add(SelectButton);

        buttonGroup1.add(RectangleButton);
        RectangleButton.setText("Rectangle");
        RectangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RectangleButtonActionPerformed(evt);
            }
        });
        add(RectangleButton);

        buttonGroup1.add(TriangleButton);
        TriangleButton.setText("Triangle");
        TriangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriangleButtonActionPerformed(evt);
            }
        });
        add(TriangleButton);

        buttonGroup1.add(OvalButton);
        OvalButton.setText("Oval");
        OvalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OvalButtonActionPerformed(evt);
            }
        });
        add(OvalButton);

        buttonGroup1.add(HexgeonButton);
        HexgeonButton.setText("Hexgeon");
        HexgeonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexgeonButtonActionPerformed(evt);
            }
        });
        add(HexgeonButton);

        RedColor.setBackground(new java.awt.Color(255, 0, 51));
        buttonGroup2.add(RedColor);
        RedColor.setForeground(new java.awt.Color(255, 255, 255));
        RedColor.setText("Red");
        RedColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedColorActionPerformed(evt);
            }
        });
        add(RedColor);

        GreenColor.setBackground(new java.awt.Color(0, 255, 0));
        buttonGroup2.add(GreenColor);
        GreenColor.setForeground(new java.awt.Color(255, 255, 255));
        GreenColor.setText("Green");
        GreenColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenColorActionPerformed(evt);
            }
        });
        add(GreenColor);

        BlackColor.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(BlackColor);
        BlackColor.setText("Black");
        BlackColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackColorActionPerformed(evt);
            }
        });
        add(BlackColor);

        BlueColor.setBackground(new java.awt.Color(0, 0, 255));
        buttonGroup2.add(BlueColor);
        BlueColor.setText("Blue");
        BlueColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueColorActionPerformed(evt);
            }
        });
        add(BlueColor);

        White.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(White);
        White.setForeground(new java.awt.Color(0, 0, 0));
        White.setText("White");
        White.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhiteActionPerformed(evt);
            }
        });
        add(White);
    }// </editor-fold>//GEN-END:initComponents

    private void RectangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RectangleButtonActionPerformed
        selectedShape = ShapeType.RECTANGLE;
        select = false;
    }//GEN-LAST:event_RectangleButtonActionPerformed

    private void OvalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OvalButtonActionPerformed
        selectedShape = ShapeType.OVAL;
        select = false;
    }//GEN-LAST:event_OvalButtonActionPerformed

    private void RedColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedColorActionPerformed
        selectedColor = Color.RED;
    }//GEN-LAST:event_RedColorActionPerformed

    private void GreenColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenColorActionPerformed
        selectedColor = Color.GREEN;
    }//GEN-LAST:event_GreenColorActionPerformed

    private void BlackColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackColorActionPerformed
       selectedColor = Color.BLACK;
    }//GEN-LAST:event_BlackColorActionPerformed

    private void BlueColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueColorActionPerformed
       selectedColor = Color.BLUE;
    }//GEN-LAST:event_BlueColorActionPerformed

    private void WhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhiteActionPerformed
       selectedColor = Color.WHITE;
       
    }//GEN-LAST:event_WhiteActionPerformed

    private void TriangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriangleButtonActionPerformed
        selectedShape = ShapeType.TRIANGLE;
        select = false;
    }//GEN-LAST:event_TriangleButtonActionPerformed

    private void HexgeonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexgeonButtonActionPerformed
        selectedShape = ShapeType.HEXGEON;
        select = false;
    }//GEN-LAST:event_HexgeonButtonActionPerformed

    private void SelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButtonActionPerformed
        select = true;
    }//GEN-LAST:event_SelectButtonActionPerformed
    public ShapeType getSelectedShape(){
        return selectedShape;
    }
    public Color getSelectedColor(){
        return selectedColor;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BlackColor;
    private javax.swing.JToggleButton BlueColor;
    private javax.swing.JToggleButton GreenColor;
    private javax.swing.JToggleButton HexgeonButton;
    private javax.swing.JToggleButton OvalButton;
    private javax.swing.JToggleButton RectangleButton;
    private javax.swing.JToggleButton RedColor;
    private javax.swing.JToggleButton SelectButton;
    private javax.swing.JToggleButton TriangleButton;
    private javax.swing.JToggleButton White;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
